### ISSUE TITLE
preimages alone don't provide enough randomness for quorum generation

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2268]
Let's say the current block height is X and in 15 seconds the nomination start for block height X+1. At this point an attacker already knows (with very high certanty) all the preimages that will provide the randomness for block X+1 as all validators share their preimage for the next 6 blocks in advance. No sane validators would start sharing their preimage for block X+1 15 seconds before the nomination starts and risk getting slashed. 

At this point an attacker also know that (with high certainty) which new validators will enroll in block X+1. Now an attacker can create his own enrollment with a carefully chosen preimage seed and manipulate the randomness we use in block X+1 to gerenate quorums. This way an attacker can force any high stake node to involve this attacker node into its quorum. To make things worse an attacker can enroll 6 nodes for block X+1 and then befoul any high stake node provided that the maximum quorum size is 7.

The attack above is very common in Ethereum and called front-running: specifically modified Ethereum nodes looking into the current transaction pool and make last minute decisions to profit on DeX trades.

---

I was thinking how to add more randomness to the quorum generation. Including the block hash of block X+1 would not help, as it is almost guaranteed that each validator will include the same set of txs in the same order in the proposed block, so very little randomness there (except maybe the timestamp that can vary from node to node). 

I was thinking that each validators might include their own random number in the ConsensusData and one of that random number would end up on the blockchain. As far as I know, no validators can influence the SCP protocol in a way that their suggested candidate will be the one that is finally externalized. We could include that random number in the blockhash and alongside with the preimages we would make it more difficult for an attacker to chose his quorum neighbors. It is far from perfect, but the current quorum generation is too easy to abuse.

Anyone has better idea?

**Comment by linked0** [comment]
> Now an attacker can create his own enrollment with a carefully chosen preimage seed

~~We could add the preimage at the height of 0 in the enrollment(aka, `first preimage`) or something like that and `commitment` which is already contained in `Enrollment`. And we can check that the `commitment` is a valid value from the `first preimage`.~~ I'm working on the concept of `very large pre-images` like 5 million pre-images([PR#2252](https://github.com/bosagora/agora/pull/2252)). I think it's very hard to choose a preimage seed to get a specific preimage on a specific height. Please let me know if there's something I missed.

**Comment by hewison-chris** [comment]
> Now an attacker can create his own enrollment with a carefully chosen preimage seed and manipulate the randomness we use in block X+1 to gerenate quorums.

This is not actually a problem for block X + 1 (maybe for X + 2: but still unlikely due to reason @linked0 mentioned above) as the `preimage`  is not used for that **new** enrol until the block after enrolment. I say **new** enrol as if it was a **re-enrol** then it has to be the next `preimage` based on height from previous enrolments.

**Comment by ferencdg** [comment]
> > Now an attacker can create his own enrollment with a carefully chosen preimage seed and manipulate the randomness we use in block X+1 to gerenate quorums.
> 
> This is not actually a problem for block X + 1 (maybe for X + 2: but still unlikely due to reason @linked0 mentioned above) as the `preimage` is not used for that **new** enrol until the block after enrolment. I say **new** enrol as if it was a **re-enrol** then it has to be the next `preimage` based on height from previous enrolments.

1.
I don't think it matters whether an attacker (still at block X), can modify the randomness for Block X+1 or Block X+2: the only thing matters is he can do it(by submitting an enrollment before the nomination happens for Block X+1) and other validators at block X+1 will have no chance to give any randomness to influence block X+2 quorum reshuffling. At block X+2 the attacker will be able to chose his quorum neighbours.

2.
@linked0 I don't think the fact that how many preimages we pregenerate matters here, the attacker knows the next 6 preimages from all other nodes. The attacker will chose his preimage(seed) at block X(by submitting a new enrollment). https://github.com/bosagora/agora/issues/2268#issuecomment-878816645

Let me know if I still misunderstand something.

**Comment by ferencdg** [comment]
Why would an attacker by the way about generating 5.000.000 preimages and not just 4000? What if he only generate 2000 and later let his enrollment expire and sell the UTXO to someone else?

(sorry I am not really familiar with preimage sharing)

**Comment by ferencdg** [comment]
also does generating 5 million preimages takes really that long of a time? He can infact pregenerate 5.000.000 preimages for different seeds for days before the attack, and just store them for the Block X+2. Also if he doesn't plan to re-enroll it is enough to gerenate 1000+ preimages.

**Comment by ferencdg** [comment]
> > > Now an attacker can create his own enrollment with a carefully chosen preimage seed and manipulate the randomness we use in block X+1 to gerenate quorums.
> > 
> > 
> > This is not actually a problem for block X + 1 (maybe for X + 2: but still unlikely due to reason @linked0 mentioned above) as the `preimage` is not used for that **new** enrol until the block after enrolment. I say **new** enrol as if it was a **re-enrol** then it has to be the next `preimage` based on height from previous enrolments.
> 
> 
> I don't think it matters whether an attacker (still at block X), can modify the randomness for Block X+1 or Block X+2: the only thing matters is he can do it(by submitting an enrollment before the nomination happens for Block X+1) and other validators at block X+1 will have no chance to give any randomness to influence block X+2 quorum reshuffling. At block X+2 the attacker will be able to chose his quorum neighbours.
> 
> 
> @linked0 I don't think the fact that how many preimages we pregenerate matters here, the attacker knows the next 6 preimages from all other nodes. The attacker will chose his preimage(seed) at block X(by submitting a new enrollment). [#2268 (comment)](https://github.com/bosagora/agora/issues/2268#issuecomment-878816645)
> 
> Let me know if I still misunderstand something.

@hewison-chris The only randomness not known in Block X that influences quorum reshuffling at Block X+2 is whether existing validators re-enroll at Block X+1 or not (I suppose that influences randomness at Block X+2, but didn't check the code). However an attacker can chose X so that no enrollment expires at X+1.

**Comment by hewison-chris** [comment]
This attack is not possible so long as at least one `validator` from any `quorum` reveals only the `pre-image` for block X or X+1 during block X nomination.  I am not saying we do not need to consider adding an extra randomness like you plan but just want to be sure we all understand the attack vector.

**Comment by ferencdg** [comment]
talked about this with Chris offline, and as he mentioned before: unless at least one of the validator didn't share the preimage for X+2 (and will share it later), the attack can happen (X+1 is almost definitely shared by everyone, unless they want to risk getting slashed). Currently we always share preimages up until block X + 6. So the attack looks like this:

1. block X is externalized, and right now we are 15 secs from starting nomination for X+1,
attacker sends enrollment just before nomination for X+1 starts with a carefully selected seed
2. X + 1 is externalized, and a quorum reshuffle happens, then the attacker sends an other enrollment(so a new quorum reshuffling will happen in X + 2)
3. X + 2 is externalized and a new quorum reshuffling happens -> the attacker was able to chose its neighbours at X + 2 based on preimages shared up until height X + 2
4. no more reshuffling will happen in subsequent blocks until someone chose to enroll again or enrollment expires

**Comment by ferencdg** [comment]
I think the best solution would be to delay the reshuffling by let's say 12 blocks after enrollment and then use the latest preimage root which was almost definitely not known by the attacker (this way we can keep our hardcoded 6 block in advance preimage sharing logic)

However it might not be so easy to implement.

**Comment by hewison-chris** [comment]
> I think the best solution would be to delay the reshuffling by let's say 12 blocks after enrollment and then use the latest preimage root which was almost definitely not known by the attacker (this way we can keep our hardcoded 6 block in advance preimage sharing logic)
> 
> However it might not be so easy to implement.

Good idea, that would even work with only a 6 block delay before a newly enrolled `validator` can join a quorum and start acting as a `validator`. Shuffles for other `validators` could still occur as normal.

**Comment by Geod24** [comment]
> At this point an attacker already knows (with very high certanty) all the preimages that will provide the randomness for block X+1 as all validators share their preimage for the next 6 blocks in advance.

Just to clarify: This is not part of the consensus rules. A node is free to change this to whatever they like. They might use a higher value, or a lower one, and they would still be conforming implementation. So for the purpose of this discussion we should assume that nodes have either provided many pre-images, if not all, and at the same time, that they only have provided one.

> At this point an attacker also know that (with high certainty) which new validators will enroll in block X+1. Now an attacker can create his own enrollment with a carefully chosen preimage seed and manipulate the randomness we use in block X+1 to gerenate quorums. This way an attacker can force any high stake node to involve this attacker node into its quorum. To make things worse an attacker can enroll 6 nodes for block X+1 and then befoul any high stake node provided that the maximum quorum size is 7.

To some extent. The attacker would have to generate at least 2016 pre-images, then keep on rebuilding the quorum configuration until it's satisfactory. Even if it does so, it would be a single node in the quorum, and any high stakes validators will have more than one quorums it is part of. Doing it 6 times *should be* computationally intensive, provided the network has enough validators. If it only has 6, like currently, yes it's much easier, but as the network grows, so will the complexity of the quorums. And the network growth will be correlated to the public's interest in it, and consequently, the coin price.

> I was thinking that each validators might include their own random number in the ConsensusData and one of that random number would end up on the blockchain.

The point of the pre-image system is to provide a safe, unbiased source of randomness, both for the node and the network.
At the node level, we use it for signatures, so that we can avoid the `R` exchange protocol when signing blocks.
At the point of the network, we use it for quorum balancing and a couple other things. Adding another random number system would essentially make pre-image useless, and would raise tons of issues that motivated the pre-image system in the first place (how do you prove that a number is random ?).

**Comment by ferencdg** [comment]
> Just to clarify: This is not part of the consensus rules. A node is free to change this to whatever they like. They might use a higher value, or a lower one, and they would still be conforming implementation. So for the purpose of this discussion we should assume that nodes have either provided many pre-images, if not all, and at the same time, that they only have provided one.

Currently hardcoded to 6 and people have no real incentive to make it lower even if they could (they can get slashed). In fact if this issue was not reported we would have kept the hardcoded 6.

> To some extent. The attacker would have to generate at least 2016 pre-images, then keep on rebuilding the quorum configuration until it's satisfactory. Even if it does so, it would be a single node in the quorum, and any high stakes validators will have more than one quorums it is part of. Doing it 6 times _should be_ computationally intensive, provided the network has enough validators. If it only has 6, like currently, yes it's much easier, but as the network grows, so will the complexity of the quorums. And the network growth will be correlated to the public's interest in it, and consequently, the coin price.

1.
Attacker can have 1.000.000 seeds pregenerated offline with all the preimages for height X+2. There is no need to generate 2016 * 1.000.000 preimages right before the attack.

2.
'computationally intensive' - it would be nice to back that up with some data. If you look at this:
https://github.com/bosagora/agora/issues/2251#issuecomment-877993870
after 10 * 24 * 6 = 1440 try the attacker has 30% chance to be able to control the quorum of a random validator (5 validators are under the control of an attacker out of 6) -> calculating the quorum reshuffling 1440 times doesn't seem computational intensive.


> The point of the pre-image system is to provide a safe, unbiased source of randomness, both for the node and the network.
> At the node level, we use it for signatures, so that we can avoid the `R` exchange protocol when signing blocks.
> At the point of the network, we use it for quorum balancing and a couple other things. Adding another random number system would essentially make pre-image useless, and would raise tons of issues that motivated the pre-image system in the first place (how do you prove that a number is random ?).

The right solution to solve the problem is here: (I think no reason to discuss an initial solution that I mentioned is far from perfect):
https://github.com/bosagora/agora/issues/2268#issuecomment-878899257

**Comment by ferencdg** [comment]
if you combine issue #2251 with #2268, then I think together they become quite serious. 

1. You can befoul validatorA (by chosing the quorums using #2268) and that validatorA will sign an externalize message. ValidatorA doesn't have to be a high-stake node.
2. Because the newly created block will never have enough signatures from other validators, it will never make into the Ledger.
3. ValidatorA starts to catch-up and share his signature on a block other than the one created at step 1.

Now ValidatorA leaked his private key (even after the fix that we no longer sign the confirm messages, but the externalize message which is done in PR #2270).

So I think either this ticket should be solved, or we should not share signatures during catchup at all (we can try to remember which externalize messages we signed, but that wouldn't help us with this: https://github.com/bosagora/agora/issues/2251#issuecomment-878064165

However not sharing signatures would also lowers security, as we might end up with blocks that is only signed by 51% percent of the validators.

**Comment by linked0** [comment]
If we could use different preimages for the commitment for enrollment and the leader selection in the above case, it should be so big problem. No attacker can create two consecutive pre-images for manipulating the leader selection in a limited time, like 10 minutes, I think.

**Comment by linked0** [comment]
I think this part of `ValidatorSet.d` should be changed also because the height of the preimage of commitment and the `enrolled` height can be different.
```
this.db.execute("INSERT OR REPLACE INTO preimages " ~
    "(key, height, preimage) VALUES (?, ?, ?)",
    enroll.utxo_key, height, enroll.commitment);
```

**Comment by hewison-chris** [comment]
This issue still assumes that all nodes will reveal their `pre-images` at least 2 blocks in advance. The plan is to have some nodes that reveal JIT to ensure randomness.
